#!/bin/bash
mkdir -p /tmp/h4ckb0x
DOCKER_PARAMS="--rm \
--network="host" \
--mount type=bind,source=$HACKBOX_PROJECT_DIR,target=/root/projects \
--mount type=bind,source=/tmp/h4ckb0x,target=/tmp"

if [ -n "$HACKBOX_PROJECT_DIR" ]; then
    if [ -f $HOME/.h4ckb0x.env ]; then 
      DOCKER_PARAMS="$DOCKER_PARAMS --env-file $HOME/.h4ckb0x.env"
    fi
    docker run $DOCKER_PARAMS -it h4ckb0x bash
else 
    echo "Error: HACKBOX_PROJECT_DIR is undefined. Please point the HACKBOX_PROJECT_DIR variable to a directory representing your h4ckb0x working directory."
fi
